In [1]:
import numpy as nm
import pandas as pd

In [2]:
country = pd.read_csv('Country.csv')

In [3]:
country.head()

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2013.0,2000.0
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011.0,2013.0,2006.0
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,NaN,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",NaN,NaN,2010.0,2013.0,2001.0
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,...,NaN,NaN,2010,NaN,NaN,Yes,2007,NaN,NaN,NaN
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,...,NaN,NaN,2011. Population data compiled from administra...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN

In [13]:
country.columns

Index(['CountryCode', 'ShortName', 'TableName', 'LongName', 'Alpha2Code',
       'CurrencyUnit', 'SpecialNotes', 'Region', 'IncomeGroup', 'Wb2Code',
       'NationalAccountsBaseYear', 'NationalAccountsReferenceYear',
       'SnaPriceValuation', 'LendingCategory', 'OtherGroups',
       'SystemOfNationalAccounts', 'AlternativeConversionFactor',
       'PppSurveyYear', 'BalanceOfPaymentsManualInUse',
       'ExternalDebtReportingStatus', 'SystemOfTrade',
       'GovernmentAccountingConcept', 'ImfDataDisseminationStandard',
       'LatestPopulationCensus', 'LatestHouseholdSurvey',
       'SourceOfMostRecentIncomeAndExpenditureData',
       'VitalRegistrationComplete', 'LatestAgriculturalCensus',
       'LatestIndustrialData', 'LatestTradeData', 'LatestWaterWithdrawalData'],
      dtype='object')

In [4]:
country.shape

(247, 31)

In [6]:
indicators = pd.read_csv('Indicators.csv')

In [7]:
indicators.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
0,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,1.335609e+02
1,Arab World,ARB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,8.779760e+01
2,Arab World,ARB,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,6.634579e+00
3,Arab World,ARB,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,8.102333e+01
4,Arab World,ARB,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,1960,3.000000e+06

In [8]:
indicators.shape

(5656458, 6)

In [15]:
data_first =  indicators[indicators['IndicatorName'] == 'Fossil fuel energy consumption (% of total)']

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [11]:
data_first.to_csv('data_first.csv')

In [12]:
data_first.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
183,Central Europe and the Baltics,CEB,Fossil fuel energy consumption (% of total),EG.USE.COMM.FO.ZS,1960,98.246903
260,East Asia & Pacific (all income levels),EAS,Fossil fuel energy consumption (% of total),EG.USE.COMM.FO.ZS,1960,91.148056
514,Euro area,EMU,Fossil fuel energy consumption (% of total),EG.USE.COMM.FO.ZS,1960,94.021507
620,Europe & Central Asia (all income levels),ECS,Fossil fuel energy consumption (% of total),EG.USE.COMM.FO.ZS,1960,93.752876
724,Europe & Central Asia (developing only),ECA,Fossil fuel energy consumption (% of total),EG.USE.COMM.FO.ZS,1960,44.199072

In [14]:
country['IncomeGroup'].value_counts()

Upper middle income     53
Lower middle income     51
High income: nonOECD    47
High income: OECD       32
Low income              31
Name: IncomeGroup, dtype: int64

In [17]:
indicators['IndicatorName'].value_counts()

Population, total                                                                                                    13484
Population growth (annual %)                                                                                         13442
Urban population (% of total)                                                                                        13415
Rural population (% of total population)                                                                             13415
Urban population                                                                                                     13374
Rural population                                                                                                     13374
Urban population growth (annual %)                                                                                   13337
Surface area (sq. km)                                                                                                13090
Land area (sq. km)                                                                                                   13086
Rural population growth (annual %)                                                                                   13061
Population density (people per sq. km of land area)                                                                  12988
Death rate, crude (per 1,000 people)                                                                                 12486
Adolescent fertility rate (births per 1,000 women ages 15-19)                                                        12485
Birth rate, crude (per 1,000 people)                                                                                 12485
Population ages 65 and above (% of total)                                                                            12426
Population, ages 15-64 (% of total)                                                                                  12426
Population, female (% of total)                                                                                      12426
Population, ages 0-14 (% of total)                                                                                   12426
Age dependency ratio (% of working-age population)                                                                   12423
Age dependency ratio, old (% of working-age population)                                                              12423
Age dependency ratio, young (% of working-age population)                                                            12423
Life expectancy at birth, male (years)                                                                               12304
Life expectancy at birth, female (years)                                                                             12304
Life expectancy at birth, total (years)                                                                              12304
Fertility rate, total (births per woman)                                                                             12266
Survival to age 65, female (% of cohort)                                                                             12258
Survival to age 65, male (% of cohort)                                                                               12258
Mortality rate, adult, male (per 1,000 male adults)                                                                  11939
Mortality rate, adult, female (per 1,000 female adults)                                                              11939
Agricultural land (sq. km)                                                                                           11751
                                                                                                                     ...
Child employment in services, female (% of female economically active children ages 7-14)                              122
Child employment in agriculture, female (% of female economically active children ages 7-14)                           122
Child employment in manufacturing, male (% of male economically active children ages 7-14)                             120
Child employment in manufacturing, female (% of female economically active children ages 7-14)                         120
Present value of external debt (current US$)                                                                           118
Net official flows from UN agencies, UNECE (current US$)                                                               114
Child employment in agriculture (% of economically active children ages 7-14)                                          114
Child employment in services (% of economically active children ages 7-14)                                             114
Coverage (%) - All Labor Market                                                                                        114
Child employment in manufacturing (% of economically active children ages 7-14)                                        113
Point-of-sale terminals (per 100,000 adults)                                                                           100
Present value of external debt (% of GNI)                                                                              100
Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)       94
Annualized average growth rate in per capita real survey mean consumption or income, total population (%)               94
Average working hours of children, study and work, ages 7-14 (hours per week)                                           90
Average working hours of children, study and work, female, ages 7-14 (hours per week)                                   90
Average working hours of children, study and work, male, ages 7-14 (hours per week)                                     90
Average working hours of children, working only, male, ages 7-14 (hours per week)                                       85
Presence of peace keepers (number of troops, police, and military observers in mandate)                                 85
Average working hours of children, working only, ages 7-14 (hours per week)                                             85
Disaster risk reduction progress score (1-5 scale; 5=best)                                                              83
Average working hours of children, working only, female, ages 7-14 (hours per week)                                     83
Children in employment, self-employed (% of children in employment, ages 7-14)                                          70
Children in employment, self-employed, male (% of male children in employment, ages 7-14)                               70
Children in employment, self-employed, female (% of female children in employment, ages 7-14)                           70
Present value of external debt (% of exports of goods, services and primary income)                                     69
Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households)                               67
Benefits incidence in poorest quintile (%) - All Labor Market                                                           67
Survey mean consumption or income per capita, bottom 40% of population (2005 PPP $ per day)                              8
Survey mean consumption or income per capita, total population (2005 PPP $ per day)                                      8
Name: IndicatorName, Length: 1344, dtype: int64

In [18]:
data_Co2 =  indicators[indicators['IndicatorName'] == 'CO2 emissions (kt)']

In [19]:
data_Co2.to_csv('data_co2.csv')